language: python
python:
  - "3.6"
sudo: false
dist: bionic
cache:
  directories:
  - $HOME/.cache/pip
before_install:
- sudo apt-get install -y --no-install-recommends automake
- sudo apt-get install -y --no-install-recommends libtool
- sudo apt-get install -y --no-install-recommends make
- sudo apt-get install -y --no-install-recommends g++
- sudo apt-get install -y --no-install-recommends libqd-dev
- sudo apt-get install -y --no-install-recommends libqhull-dev
- sudo apt-get install -y --no-install-recommends libmumps-seq-dev
- sudo apt-get install -y --no-install-recommends liblapack-dev
- sudo apt-get install -y --no-install-recommends libopenblas-dev
- sudo apt-get install -y --no-install-recommends libpython3-dev
- sudo apt-get install -y --no-install-recommends ufraw
- sudo apt-get install -y --no-install-recommends imagemagick
- sudo apt-get install -y --no-install-recommends fig2dev
- sudo apt-get install -y --no-install-recommends texlive
- sudo apt-get install -y --no-install-recommends xzdec
- sudo apt-get install -y --no-install-recommends fig2ps
- sudo apt-get install -y --no-install-recommends gv
- pip install -r requirements.txt
addons:
  apt:
    update: true
script:
- bash autogen.sh
- export CXXFLAGS=-coverage
- export LDFLAGS=-coverage
- export CPPFLAGS=-coverage
- export CFLAGS=-coverage
- export FCFLAGS=-coverage
- ./configure --with-pic
- make -j8
- make -j8 check
- sudo perl -p -i -e 's/^.*"EPS".*\n//g' /etc/ImageMagick-*/policy.xml
- sudo perl -p -i -e 's/^.*"PS".*\n//g'  /etc/ImageMagick-*/policy.xml
- sudo perl -p -i -e 's/^.*"PDF".*\n//g' /etc/ImageMagick-*/policy.xml
- sudo perl -p -i -e 's/^.*"XPS".*\n//g' /etc/ImageMagick-*/policy.xml
- (cd doc/sphinx; make html)
after_success:
- bash <(curl -s https://codecov.io/bash)
